### ISSUE TITLE
[Features] Shuffle Command

### ISSUE THREAD

**Issue by superhe11** [zhycorp/disc-11#61]
Plz make a shuffle commands, cause i have ~2hrs playlist and its hard to shuffle myself

**Comment by mozartrafi** [comment]
@Hazmi35 are you ok with this?

**Comment by Hazmi35** [comment]
this is your version, unless the author opens an issue on the [original](https://github.com/Hazmi35/jukebox) repository

**Comment by mozartrafi** [comment]
See? Go ahead.

**Comment by Hazmi35** [comment]
You know you can try implements it on this repository right? if someone needs it on the original repo, I'll try backporting from this

**Comment by KurokuTetsuya** [comment]
kntql

**Comment by mzrtamp** [comment]
Thanks for your old request

**Comment by mzrtamp** [comment]
Done in #460
