### ISSUE TITLE
Create app App creation failed. Please ensure you have valid values in the above form fields.  Configure environment There was an issue setting up your app environment.  could not find the source blob

### ISSUE THREAD

**Issue by Jingexz01** [zhycorp/disc-11#72]
I get this error when running on Heroku.

Create app
App creation failed. Please ensure you have valid values in the above form fields.

Configure environment
There was an issue setting up your app environment.

could not find the source blob

Please help me in this error.

**Comment by mozartrafi** [comment]
Hi @Jingexz01 :wave:

**We are not supporting [Heroku](https://heroku.com)**
But you still can host some by forking this project, 
then commit to creating new file names Procfile with `node .` as Dynos thing.

If you have other questions, please come to [https://discord.gg/zhycorp](https://discord.gg/zhycorp)
